---
title: "Wrangle transcripts"
output: html_notebook
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(jsonlite)
library(ggplot2)

ParseJSONColumn <- function(x) {
  str_c("[ ", str_c(x, collapse = ",", sep=" "), " ]")  %>% 
    fromJSON(flatten = T)
}

pilot_start=lubridate::ymd('2023-07-07') 
pilot_end=lubridate::ymd('2023-07-12')

real_start=lubridate::ymd('2023-07-17')
real_end=lubridate::ymd('2023-08-09')

data_source <- "data/rounds.csv"
player_source <- "data/players.csv"

pilot_ids <- str_c("id", 3:12) # Ids 1, 2 were adult pilot test 

real_ids <-str_c("id", c(13:16, 19:36, 39:54, 57:58)) # skipping kids who didn't complete enough trials
```

# Empirica output prep

```{r}

players <- read_csv(here(player_source)) |> filter(id %in% real_ids) %>% select(id, playerId=`_id`) 

games <- read_csv(here("data/games.csv"), col_types="ccc")|> filter(is.na(exclude)) |>  mutate(offset_sec=lubridate::ms(offset) |> lubridate::period_to_seconds()) |> select(-offset)

```

```{r}

raw_data <- read.csv(here(data_source), header = TRUE) %>% 
  filter(createdAt >= real_start) %>%
  filter(createdAt <= real_end) %>% 
  rename_with(~ gsub("data.", "", .x, fixed = TRUE)) %>% 
  select(-chat) |> 
  pivot_longer(cols=starts_with('player'), names_to=c("playerId", "info"), names_prefix="player_", names_sep="_",
               values_to="values", values_transform=as.character, values_drop_na=T) %>% 
  filter(values!="") %>% 
  filter(playerId!=speaker) %>% 
  pivot_wider(names_from=info, values_from=values) |> 
  left_join(players, by=c("playerId")) |> 
  select(-playerId) |> 
  rename(playerId=id) |> 
  left_join(players, by=c("speaker"="playerId")) |> 
  select(-speaker) |> 
  rename(speaker=id) %>% 
  left_join(games) |> 
  rename(game=gameConfig) |> 
  select(-gameId, -offset_sec) |> 
  filter(!is.na(game)) |> 
  mutate(time=as.numeric(time))




label_image <- function(string){
  new_string <- case_when(
    string=="/experiment/B1.jpg" ~ "walk",
    string=="/experiment/D1.jpg" ~ "swim",
    string=="/experiment/E1.jpg" ~ "jump",
    string=="/experiment/I1.jpg" ~ "hold",
    string=="/experiment/banana.png"~ "banana",
    string=="/experiment/bird.jpeg" ~ "bird",
    string=="/experiment/dog.png" ~ "dog",
    string =="/experiment/apple.png" ~ "apple"
  )
  return(new_string)
}

less_raw_data <- raw_data %>% select(game, target, distractor, trialNum, targetNum, repNum, response, correct, time, listener=playerId, speaker) %>% 
  mutate(across(c(target, distractor, response), ~ label_image(.x))) %>% write_csv(here("data/clean_data.csv"))
```

```{r}
#just for pilot, need to fix offset
#fix <- raw_data |> filter(trialNum==0) |> select(game, time)

#real_offset <- games |> left_join(fix, by=c("gameConfig"="game")) |> mutate(offset_sec=offset_sec-time/1000)

real_offset <- games

```

# Transcript wrangle - new

```{r}



wrangle_transcript <- function(game_num){
 read_csv(here("data/clean_transcripts", str_c(game_num,".csv")), show_col_types=F) |> 
  select(start, end, text, speaker, trial, role, echo, description, backchannel) |> 
    fill(trial) %>% 
  mutate(start=start/1000, end=end/1000) |> 
    nest(data=c(start, end, text, speaker, trial, role, echo, description, backchannel))
}

#wrangle_transcript("game41") %>% unnest(data) %>% View()

real_offset$transcripts <- map_df(real_offset$gameConfig, wrangle_transcript)

transcripts <- real_offset |> unnest(transcripts) |> unnest(data)

# this section is janky as hell, but it does work

```


```{r}

stages <- read_csv(here("data/stages.csv")) |> select(index, gameId, startTimeAt) |> group_by(gameId)

gameStarts <- stages |> filter(index==0) |> rename(first=startTimeAt) |> select(-index)

stage_timing <- stages |> left_join(gameStarts) |>
  mutate(rel_time=startTimeAt-first) |> 
  mutate(rel_time=lubridate::as.period(rel_time) |> lubridate::period_to_seconds()) |> 
   mutate(trialNum=index/2,
          start=rel_time,
          end=lead(rel_time)) |> 
  select(gameId, trialNum,start, end) |>  left_join(games) |>  ungroup() |> 
  mutate(trialNumStart=trialNum, trialNumEnd=trialNum) |> 
  select(game=gameConfig, trialNumStart, trialNumEnd, start, end) |> filter(!is.na(game)) |> filter(!is.na(start)) |> filter(!is.na(end))
```



```{r}
timed_transcripts <-  transcripts |>
  mutate(start=start-offset_sec, end=end-offset_sec) |> 
  select(-offset_sec, -gameId) |> 
  mutate(trialNumStart=NA, trialNumEnd=NA) |> 
  rename(game=gameConfig) |> 
  bind_rows(stage_timing) |> 
  group_by(game) |> 
  arrange(start) |> 
  fill(trialNumStart) |> 
  arrange(end) |> 
  fill(trialNumEnd, .direction="up") |> 
  arrange(game) |> 
  filter(!is.na(text))



echoes <- timed_transcripts %>% select(game,trial, echo) %>% filter(echo=="Y") %>% unique()

trial_timing <- stage_timing %>% select(game, trial=trialNumStart, trial_start=start)

transcript_full <- timed_transcripts %>% select(-echo, -exclude) %>% left_join(echoes) %>% 
  left_join(trial_timing) %>% 
  rename(start_time=start, end_time=end) %>% 
  write_csv(here("data/timed_transcript.csv"))
```

# Checks
```{r}
# Quick check -- for kid talking, so auto-trial and hand-trial align?

transcript_full %>% filter(!is.na(trialNumStart)) %>% filter(str_detect(speaker, "id")) %>% filter(!is.na(role)) %>% filter(trial!=trialNumStart)

# we'll go with the by-hand method -- these mostly seem to be when there's a wide span of time! possibly due to whisper being silly or us hand filling due to whisper missing things



```

checks on data:
* anything that has a description should be from a speaker and have Y for backchannel
* anything that has a Y for backchannel should be from a child

```{r}
transcript_full %>% filter(!is.na(description)) %>% filter(is.na(backchannel))
transcript_full %>% filter(!is.na(description)) %>% ungroup() %>% select(role) %>% unique()
transcript_full %>% filter(backchannel=="Y") %>% ungroup() %>% select(role) %>% unique() 
transcript_full %>% filter(backchannel=="Y") %>% ungroup() %>% filter(!str_detect(speaker,"id"))
```

# Sbert data prep

```{r}
transcript <- read_csv(here("data/timed_transcript.csv"))

dat <- read_csv(here("data/clean_data.csv")) %>% select(trial=trialNum, game, target, distractor)

transcript %>% filter(!is.na(description)) %>% group_by(trial, game) %>% 
  summarize(words=str_c(description, sep=" ", collapse=", ")) %>% left_join(dat) %>% write_csv(here("data/pre_sbert.csv"))


```

```{r}
library(reticulate)
np <- import("numpy")
mat = np$load(here('data/post_sbert.npy'))
saveRDS(mat,here('data/post_sbert.RData'))
```

```{r}
sbert <- read_csv(here("data/pre_sbert.csv")) %>% bind_cols(read_rds(here("data/post_sbert.RData")) %>% 
  as_tibble())

### helper funcs
get_sim_matrix = function(df, F_mat, method = 'cosine') {
  feats = F_mat[df$feature_ind,]
  if(method == 'cor') {
    return(cor(t(feats), method = 'pearson'))
  } else if (method == 'euclidean') {
    return(as.matrix(dist(feats, method = 'euclidean')))
  } else if (method == 'cosine') {
    return(as.matrix(lsa::cosine(t(feats))))
  } else {
    stop(paste0('unknown method', method))
  }
}

# note this does de-duplicated version
flatten_sim_matrix <- function(cormat, ids) {
  ut <- upper.tri(cormat)
  data.frame(
    dim1 = ids[row(cormat)[ut]],
    dim2 = ids[col(cormat)[ut]],
    sim  = as.numeric(cormat[ut])
  ) %>%
    mutate(dim1 = as.character(dim1),
           dim2 = as.character(dim2))
}


make_across_df <- function(M_mat, F_mat, method) {
  M_mat %>%
    do(flatten_sim_matrix(get_sim_matrix(., F_mat, method = method),
                          as.character(.$combinedId)))
}

### funcs
  F_mat <- sbert%>% select(starts_with("V")) %>% as.matrix() #Features
  M_mat <- sbert %>% select(-starts_with("V")) %>% mutate(feature_ind=row_number())

similarities <- M_mat %>%
    mutate(combinedId=str_c(game,trial,sep="_")) %>%
    make_across_df(F_mat, 'cosine') %>%
    separate(dim1, into=c("game1","trial1"), convert=T, sep="_") %>%
    separate(dim2, into=c("game2","trial2"), convert=T, sep="_") %>%
    mutate(sim = ifelse(is.nan(sim), NA, sim)) %>% write_rds(here("data/similarities.rds"))
 
```
