---
title: "demog"
format: html
---

```{r}
library(tidyverse)
library(here)
raw_demog <- read_csv(here("demographics.csv"))
```


```{r}
expt_1 <- read_csv(here("data/expt_1/clean_data.csv")) |>
  select(game, speaker, listener) |>
  pivot_longer(c("speaker", "listener"), values_to = "id") |>
  select(-name) |>
  unique() |>
  mutate(expt = 1)



expt_2 <- read_csv(here("data/expt_2/clean_data.csv")) |>
  select(game, speaker, listener) |>
  pivot_longer(c("speaker", "listener"), values_to = "id") |>
  select(-name) |>
  unique() |>
  mutate(expt = 2) 


kids <- expt_1 |> bind_rows(expt_2) # included kids!
```

```{r}
demogs <- raw_demog |>
  mutate(
    date_test = mdy(date_test),
    date_birth = mdy(date_birth)
  ) |>
  select(id=sid, included, date_test, date_birth, hispanic, ethnicity, gender) |> 
  full_join(kids) |>
  filter(!is.na(included)) |>
  mutate(
    age_days = (date_test - date_birth) |> as.numeric(),
    age_month = floor(age_days / 30.43)
  ) |>
  select(-age_days) |>
  mutate(gender=str_to_lower(gender)) |> 
  select(expt, id, game, gender, age_month, ethnicity, hispanic) 

demogs |> filter(expt==1) |> write_csv(here("data/expt_1/clean_demog.csv"))

demogs |> filter(expt==2) |> write_csv(here("data/expt_2/clean_demog.csv"))

```

# expt 3

```{r}

expt_3_demog <- read_csv(here("expt_3_demog.csv"))

expt_3 <- read_csv(here("data/expt_3/clean_data.csv")) |>
  select(game, speaker, listener) |>
  pivot_longer(c("speaker", "listener"), values_to = "id") |>
  select(-name) |>
  unique() |> 
  mutate(expt=3)

expt_3_demog <- read_csv(here("expt_3_demog.csv")) |> 
 mutate(
    date_test = mdy(date_test),
    date_birth = ymd(date_birth),
    id=str_c("id", SID)
  ) |>
  select(id, date_test, date_birth, hispanic, ethnicity, gender) |> 
  full_join(expt_3) |> 
  filter(!is.na(game)) |> 
  mutate(
    age_days = (date_test - date_birth) |> as.numeric(),
    age_month = floor(age_days / 30.43)
  ) |>
  select(-age_days) |>
  mutate(gender=str_to_lower(gender)) |> 
  select(expt, game, id, gender, age_month, ethnicity, hispanic) |> write_csv(here("data/expt_3/clean_demog.csv"))

```


