---
title: "Wrangle transcripts"
output: html_notebook
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(jsonlite)
library(ggplot2)

ParseJSONColumn <- function(x) {
  str_c("[ ", str_c(x, collapse = ",", sep=" "), " ]")  %>% 
    fromJSON(flatten = T)
}

data_source <- "data/expt_1/rounds.csv"
player_source <- "data/expt_1/players.csv"

```

# Empirica output prep

```{r}

players <- read_csv(here(player_source)) |> select(id, playerId=`_id`) 


```

```{r}

raw_data <- read.csv(here(data_source), header = TRUE) %>% 
  rename_with(~ gsub("data.", "", .x, fixed = TRUE)) %>% 
  select(-chat) |> 
  pivot_longer(cols=starts_with('player'), names_to=c("playerId", "info"), names_prefix="player_", names_sep="_",
               values_to="values", values_transform=as.character, values_drop_na=T) %>% 
  filter(values!="") %>% 
  filter(playerId!=speaker) %>% 
  pivot_wider(names_from=info, values_from=values) |> 
  left_join(players, by=c("playerId")) |> 
  select(-playerId) |> 
  rename(playerId=id) |> 
  left_join(players, by=c("speaker"="playerId")) |> 
  select(-speaker) |> 
  rename(speaker=id)




label_image <- function(string){
  new_string <- case_when(
    string=="/experiment/B1.jpg" ~ "walk",
    string=="/experiment/D1.jpg" ~ "swim",
    string=="/experiment/E1.jpg" ~ "jump",
    string=="/experiment/I1.jpg" ~ "hold",
    string=="/experiment/banana.png"~ "banana",
    string=="/experiment/bird.jpeg" ~ "bird",
    string=="/experiment/dog.png" ~ "dog",
    string =="/experiment/apple.png" ~ "apple"
  )
  return(new_string)
}

less_raw_data <- raw_data %>% select(gameId, target, distractor, trialNum, targetNum, repNum, response, correct, time, listener=playerId, speaker) %>% 
  mutate(across(c(target, distractor, response), ~ label_image(.x))) %>%
 inner_join(read_csv(here("data/expt_1/link_transcripts.csv")) |> select(gameId, game)) |> 
write_csv(here("data/expt_1/clean_data.csv"))

```


# Transcript wrangle
```{r}
wrangle_transcript <- function(game_num) {
  if(file.exists(here("data/expt_1/raw_transcripts", str_c(game_num, ".csv")))){
  file = read_csv(here("data/expt_1/raw_transcripts", str_c(game_num, ".csv")))
  }
  else{
    if(file.exists(here("data/expt_1/raw_transcripts/exclude/", str_c(game_num, ".csv")))){
        file = read_csv(here("data/expt_1/raw_transcripts/exclude/", str_c(game_num, ".csv")))
        }
    else{
      file=tibble(start=NA, end=NA, text=NA, speaker=NA, trial=NA, role=NA, echo=NA, description=NA, on_topic=NA)
    }
  }
  file|>
    select(start, end, text, speaker, trial, role, echo, description,on_topic) |>
    fill(trial) |> 
    mutate(start = start / 1000, end = end / 1000) |>
   nest(data = c(start, end, text, speaker, trial, role, echo, description, on_topic))

}

transcripts <- read_csv(here("data/expt_1/link_transcripts.csv")) |> 
  select(gameId, game) |>
  mutate(transcript = map_df(game, wrangle_transcript)) |>
  unnest(transcript) |>
  unnest(data)


write_csv(transcripts, here("data/expt_1/transcripts.csv"))
```





# Sbert data prep

```{r}
transcript <- read_csv(here("data/expt_1/transcripts.csv"))


dat <- read_csv(here("data/expt_1/clean_data.csv")) %>% select(trial = trialNum, gameId, target, distractor)

transcript %>%
  filter(!is.na(description)) %>%
  group_by(trial, gameId) %>%
  mutate(trial = as.numeric(trial)) |>
  filter(trial > 1) |>
  summarize(words = str_c(description, sep = " ", collapse = ", ")) %>%
  left_join(dat) %>%
  write_csv(here("data/expt_1/pre_sbert.csv"))

```

```{r}
library(reticulate)
np <- import("numpy")
mat = np$load(here('data/expt_1/post_sbert.npy'))
saveRDS(mat,here('data/expt_1/post_sbert.RData'))
```

```{r}
sbert <- read_csv(here("data/expt_1/pre_sbert.csv")) %>% bind_cols(read_rds(here("data/expt_1/post_sbert.RData")) %>% 
  as_tibble())

### helper funcs
get_sim_matrix = function(df, F_mat, method = 'cosine') {
  feats = F_mat[df$feature_ind,]
  if(method == 'cor') {
    return(cor(t(feats), method = 'pearson'))
  } else if (method == 'euclidean') {
    return(as.matrix(dist(feats, method = 'euclidean')))
  } else if (method == 'cosine') {
    return(as.matrix(lsa::cosine(t(feats))))
  } else {
    stop(paste0('unknown method', method))
  }
}

# note this does de-duplicated version
flatten_sim_matrix <- function(cormat, ids) {
  ut <- upper.tri(cormat)
  data.frame(
    dim1 = ids[row(cormat)[ut]],
    dim2 = ids[col(cormat)[ut]],
    sim  = as.numeric(cormat[ut])
  ) %>%
    mutate(dim1 = as.character(dim1),
           dim2 = as.character(dim2))
}


make_across_df <- function(M_mat, F_mat, method) {
  M_mat %>%
    do(flatten_sim_matrix(get_sim_matrix(., F_mat, method = method),
                          as.character(.$combinedId)))
}

### funcs
  F_mat <- sbert%>% select(starts_with("V")) %>% as.matrix() #Features
  M_mat <- sbert %>% select(-starts_with("V")) %>% mutate(feature_ind=row_number())

similarities <- M_mat %>%
    mutate(combinedId=str_c(gameId,trial,sep="_")) %>%
    make_across_df(F_mat, 'cosine') %>%
    separate(dim1, into=c("game1","trial1"), convert=T, sep="_") %>%
    separate(dim2, into=c("game2","trial2"), convert=T, sep="_") %>%
    mutate(sim = ifelse(is.nan(sim), NA, sim)) %>% write_rds(here("data/expt_1/similarities.rds"))
 
```
